props:
  buildingid-mapa:
    12472: http://fx.sh.189.cn/mininet/wap/dxzq/detail/3677/00.html?jobNumber=12472
    12515: http://fx.sh.189.cn/mininet/wap/dxzq/detail/3677/00.html?jobNumber=12515
    test: http://fx.sh.189.cn/mininet/wap/dxzq/detail/3677/00.html?jobNumber=test123
    test111: http://fx.sh.189.cn/mininet/wap/dxzq/detail/3677/00.html?jobNumber=shangcj
