spring:
  datasource:
    url: jdbc:mysql://localhost/dataflowdb
    username: root
    password: admin
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      connection-timeout: 60000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 100
      max-idle: 3
      max-wait: 30
      min-idle: 1
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: false
    hibernate:
      #ddl-auto: update
      naming:
        physical-strategy: net.unitedcloud.chang.util.hibernate.ImprovedNamingStrategy
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: true
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      javax.persistence.sharedCache.mode: ENABLE_SELECTIVE
  mvc:
    servlet:
      load-on-startup: 1
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
    static-path-pattern: /WEB-INF/**
    
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh,health,info #must add quotes if you want to include (or exclude) all endpoints, "*" represents all
  endpoint:
    health:
      show-details: always #default never
   
